redis:
  host: localhost
  port: 6379
  password: "e44fuT2mQM2hr437N5DTA99rK8xW8RhRAMmSm9LQ4FcnXx7bf5e8VpwXKquYzBvTpnKjUTthqq3"
  key: "Hub-1"

sending_cooldown: 6000 # 20 (ticks) = 1 (sec) || 6000 (ticks) = 5 (minutes)
