mongo:
  user: "root"
  password: "pass"
  address: "127.0.0.1"
  port: "27017"
  database: "test"
  collection: "products"
  # Si el link es mongodb+srv poner esto en true
  srv: false
  # Poner los parametros sin el ?
  params: "authSource=admin"

runnable:
  seconds: 300

server_name: "test"
